import jsPDF from 'jspdf';
import { createEvents, EventAttributes } from 'ics';
import prisma from '../database/prisma';

// Inferred Prisma types
type Itinerary = NonNullable<Awaited<ReturnType<typeof prisma.itinerary.findUnique>>>;
type ItineraryItem = NonNullable<Awaited<ReturnType<typeof prisma.itineraryItem.findUnique>>>;

/**
 * Service for exporting itineraries in various formats
 */
export class ItineraryExportService {
  /**
   * Generate PDF document for itinerary
   */
  async generatePDF(itinerary: Itinerary & { items: ItineraryItem[] }): Promise<Buffer> {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let y = 20;

    // Helper to add new page if needed
    const checkPageBreak = (height: number = 10) => {
      if (y + height > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        y = 20;
      }
    };

    // Header with gradient effect (simulated)
    doc.setFillColor(251, 146, 60); // Orange
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.text('DreamScape Itinerary', pageWidth / 2, 15, { align: 'center' });

    doc.setFontSize(14);
    doc.text(itinerary.title, pageWidth / 2, 30, { align: 'center' });

    y = 50;
    doc.setTextColor(0, 0, 0);

    // Trip Information
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Trip Details', margin, y);
    y += 8;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(`Dates: ${this.formatDate(itinerary.startDate)} - ${this.formatDate(itinerary.endDate)}`, margin, y);
    y += 6;

    if (itinerary.destinations.length > 0) {
      doc.text(`Destinations: ${itinerary.destinations.join(', ')}`, margin, y);
      y += 6;
    }

    const duration = Math.ceil((new Date(itinerary.endDate).getTime() - new Date(itinerary.startDate).getTime()) / (1000 * 60 * 60 * 24));
    doc.text(`Duration: ${duration} days`, margin, y);
    y += 12;

    // Timeline Section
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Timeline', margin, y);
    y += 10;

    // Sort items chronologically
    const sortedItems = [...itinerary.items].sort((a, b) =>
      new Date(a.startDate).getTime() - new Date(b.startDate).getTime()
    );

    // Group items by date
    const itemsByDate = this.groupItemsByDate(sortedItems);

    for (const [date, items] of Object.entries(itemsByDate)) {
      checkPageBreak(15);

      // Date header
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setFillColor(249, 250, 251); // Light gray
      doc.rect(margin - 5, y - 5, pageWidth - 2 * margin + 10, 10, 'F');
      doc.text(this.formatDate(new Date(date)), margin, y);
      y += 12;

      // Items for this date
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);

      for (const item of items) {
        checkPageBreak(25);

        // Type badge
        const typeColor = this.getTypeColor(item.type);
        doc.setFillColor(typeColor.r, typeColor.g, typeColor.b);
        doc.roundedRect(margin, y - 4, 20, 6, 2, 2, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.text(item.type, margin + 10, y, { align: 'center' });

        // Item details
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text(item.title, margin + 25, y);
        y += 6;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.text(`Time: ${this.formatTime(item.startDate)} - ${this.formatTime(item.endDate)}`, margin + 25, y);
        y += 5;

        doc.text(`Location: ${item.location}`, margin + 25, y);
        y += 5;

        if (item.description) {
          const descLines = doc.splitTextToSize(item.description, pageWidth - 2 * margin - 30);
          doc.setTextColor(100, 100, 100);
          doc.text(descLines, margin + 25, y);
          y += descLines.length * 5;
        }

        y += 5; // Space between items
      }

      y += 5; // Space between dates
    }

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Generated by DreamScape | Page ${i} of ${pageCount}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
    }

    // Convert to buffer
    const pdfBlob = doc.output('arraybuffer');
    return Buffer.from(pdfBlob);
  }

  /**
   * Generate iCal file for calendar import
   */
  generateICal(itinerary: Itinerary & { items: ItineraryItem[] }): string {
    const events: EventAttributes[] = itinerary.items.map((item) => {
      const start = new Date(item.startDate);
      const end = new Date(item.endDate);

      return {
        start: [start.getFullYear(), start.getMonth() + 1, start.getDate(), start.getHours(), start.getMinutes()],
        end: [end.getFullYear(), end.getMonth() + 1, end.getDate(), end.getHours(), end.getMinutes()],
        title: `${item.type}: ${item.title}`,
        description: item.description || undefined,
        location: item.location,
        status: 'CONFIRMED',
        busyStatus: 'BUSY',
        organizer: { name: 'DreamScape', email: 'noreply@dreamscape.com' },
        categories: [item.type, 'Travel', itinerary.title]
      };
    });

    const { error, value } = createEvents(events);

    if (error) {
      throw new Error(`Failed to generate iCal: ${error.message}`);
    }

    return value || '';
  }

  /**
   * Send email summary (requires email service integration)
   */
  async sendEmailSummary(
    itinerary: Itinerary & { items: ItineraryItem[] },
    recipientEmail: string,
    recipientName: string
  ): Promise<void> {
    // TODO: Integrate with actual email service (SendGrid, AWS SES, etc.)
    // For now, we'll generate the HTML template that would be sent

    const htmlContent = this.generateEmailTemplate(itinerary, recipientName);

    // In production, you would use an email service like:
    // await emailService.send({
    //   to: recipientEmail,
    //   subject: `Your DreamScape Itinerary: ${itinerary.title}`,
    //   html: htmlContent
    // });

    // For now, just log that email would be sent
    console.log('Email would be sent to:', recipientEmail);
    console.log('Email content generated successfully');

    // Simulate async operation
    await new Promise(resolve => setTimeout(resolve, 100));
  }

  /**
   * Generate HTML email template
   */
  private generateEmailTemplate(
    itinerary: Itinerary & { items: ItineraryItem[] },
    recipientName: string
  ): string {
    const sortedItems = [...itinerary.items].sort((a, b) =>
      new Date(a.startDate).getTime() - new Date(b.startDate).getTime()
    );

    const itemsByDate = this.groupItemsByDate(sortedItems);

    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your DreamScape Itinerary</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; margin: 0; padding: 0; background-color: #f9fafb; }
    .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }
    .header { background: linear-gradient(135deg, #fb923c 0%, #ec4899 100%); padding: 40px 20px; text-align: center; color: white; }
    .header h1 { margin: 0; font-size: 28px; }
    .header p { margin: 10px 0 0; font-size: 16px; opacity: 0.95; }
    .content { padding: 30px 20px; }
    .info-box { background-color: #fef3c7; border-left: 4px solid #fb923c; padding: 15px; margin-bottom: 20px; border-radius: 4px; }
    .date-section { margin-bottom: 30px; }
    .date-header { background-color: #f3f4f6; padding: 12px; border-radius: 6px; font-weight: bold; color: #1f2937; margin-bottom: 15px; }
    .item { border-left: 3px solid #e5e7eb; padding-left: 15px; margin-bottom: 20px; }
    .item-type { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: bold; color: white; margin-bottom: 8px; }
    .item-type.FLIGHT { background-color: #3b82f6; }
    .item-type.HOTEL { background-color: #10b981; }
    .item-type.ACTIVITY { background-color: #f59e0b; }
    .item-title { font-size: 16px; font-weight: bold; color: #111827; margin: 8px 0; }
    .item-details { font-size: 14px; color: #6b7280; line-height: 1.6; }
    .cta-button { display: inline-block; background: linear-gradient(135deg, #fb923c 0%, #ec4899 100%); color: white; padding: 14px 30px; text-decoration: none; border-radius: 8px; margin: 20px 0; font-weight: bold; }
    .footer { background-color: #f9fafb; padding: 30px 20px; text-align: center; color: #6b7280; font-size: 14px; }
    .footer a { color: #fb923c; text-decoration: none; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🌟 ${itinerary.title}</h1>
      <p>Your personalized travel itinerary is ready!</p>
    </div>

    <div class="content">
      <p>Hi ${recipientName},</p>
      <p>Your DreamScape itinerary is all set. Here's what you have planned:</p>

      <div class="info-box">
        <strong>📅 Dates:</strong> ${this.formatDate(itinerary.startDate)} - ${this.formatDate(itinerary.endDate)}<br>
        ${itinerary.destinations.length > 0 ? `<strong>📍 Destinations:</strong> ${itinerary.destinations.join(', ')}<br>` : ''}
        <strong>📊 Total Items:</strong> ${itinerary.items.length}
      </div>

      ${Object.entries(itemsByDate).map(([date, items]) => `
        <div class="date-section">
          <div class="date-header">📆 ${this.formatDate(new Date(date))}</div>
          ${items.map(item => `
            <div class="item">
              <span class="item-type ${item.type}">${item.type}</span>
              <div class="item-title">${item.title}</div>
              <div class="item-details">
                ⏰ ${this.formatTime(item.startDate)} - ${this.formatTime(item.endDate)}<br>
                📍 ${item.location}
                ${item.description ? `<br>${item.description}` : ''}
              </div>
            </div>
          `).join('')}
        </div>
      `).join('')}

      <center>
        <a href="https://dreamscape.com/planner/${itinerary.id}" class="cta-button">
          View Full Itinerary
        </a>
      </center>

      <p style="margin-top: 30px; color: #6b7280; font-size: 14px;">
        💡 <strong>Tip:</strong> Download the PDF or add to your calendar for offline access!
      </p>
    </div>

    <div class="footer">
      <p><strong>DreamScape</strong> - Your journey, perfectly planned</p>
      <p>
        <a href="https://dreamscape.com">Visit Website</a> |
        <a href="https://dreamscape.com/support">Support</a> |
        <a href="https://dreamscape.com/unsubscribe">Unsubscribe</a>
      </p>
      <p style="margin-top: 15px; font-size: 12px;">
        © ${new Date().getFullYear()} DreamScape. All rights reserved.
      </p>
    </div>
  </div>
</body>
</html>
    `.trim();
  }

  // Helper methods

  private formatDate(date: Date | string): string {
    const d = new Date(date);
    return d.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  }

  private formatTime(date: Date | string): string {
    const d = new Date(date);
    return d.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  private groupItemsByDate(items: ItineraryItem[]): Record<string, ItineraryItem[]> {
    return items.reduce((acc, item) => {
      const dateKey = new Date(item.startDate).toISOString().split('T')[0];
      if (!acc[dateKey]) {
        acc[dateKey] = [];
      }
      acc[dateKey].push(item);
      return acc;
    }, {} as Record<string, ItineraryItem[]>);
  }

  private getTypeColor(type: string): { r: number; g: number; b: number } {
    switch (type) {
      case 'FLIGHT':
        return { r: 59, g: 130, b: 246 }; // Blue
      case 'HOTEL':
        return { r: 16, g: 185, b: 129 }; // Green
      case 'ACTIVITY':
        return { r: 245, g: 158, b: 11 }; // Orange
      default:
        return { r: 107, g: 114, b: 128 }; // Gray
    }
  }
}
